apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-k8s-scaling
  region: eu-north-1
  version: '1.28'
  tags:
    karpenter.sh/discovery: eks-k8s-scaling

iam:
  withOIDC: true
  serviceAccounts:
  - metadata:
      name: aws-load-balancer-controller
      namespace: kube-system
    wellKnownPolicies:
      awsLoadBalancerController: true

karpenter:
  version: 'v0.29.0'
  createServiceAccount: true
  defaultInstanceProfile: 'KarpenterNodeInstanceProfile'
  withSpotInterruptionQueue: true

vpc:
  clusterEndpoints:
    privateAccess: true
    publicAccess: true

cloudWatch:
  clusterLogging:
    enableTypes: ["*"]

managedNodeGroups:
  - name: eks-k8s-scaling-ng
    instanceType: t3.medium
    minSize: 1
    maxSize: 5
    desiredCapacity: 3
    volumeSize: 20
    ssh:
      allow: false
    labels: {role: worker}
    tags:
      nodegroup-role: worker
    iam:
      withAddonPolicies:
        albIngress: true
        awsLoadBalancerController: true
        cloudWatch: true