apiVersion: kube-green.com/v1alpha1
kind: SleepInfo
metadata:
  name: weekend-hours
spec:
  weekdays: "6-7"
  sleepAt: "20:00"
  wakeUpAt: "08:00"
  timeZone: "Europe/Rome"
  suspendCronJobs: true
  excludeRef:
    - apiVersion: "apps/v1"
      kind:       Deployment
      name:       no-sleep-deployment
    - matchLabels: 
        kube-green.dev/exclude: "true"