apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: keda
  namespace: flux-system
spec:
  chart:
    spec:
      chart: keda
      sourceRef:
        kind: HelmRepository
        name: kedacore
      version: "2.11.1"
  interval: 1h0m0s
  releaseName: keda
  targetNamespace: keda
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rabbitmq
  namespace: flux-system
spec:
  chart:
    spec:
      chart: rabbitmq
      sourceRef:
        kind: HelmRepository
        name: bitnami
      version: "12.0.4"
  interval: 1h0m0s
  releaseName: rabbitmq
  targetNamespace: default
  values:
    auth:
      username: user
      password: PASSWORD