apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: cron-scaler
  namespace: default
spec:
  scaleTargetRef:
    name: sleep-deployment
  triggers:
  - type: cron
    metadata:
      timezone: Europe/Berlin
      start: 30 * * * *
      end: 45 * * * *
      desiredReplicas: "10"